### ISSUE TITLE
Saving folder expansion state not working

### ISSUE THREAD

**Issue by dcalhoun** [sQu1rr/nerd-treeview#10]
Unless I'm misunderstanding the meaning of "saving folder expansion state" from the [README](https://github.com/sQu1rr/nerd-treeview#tree-modification), this ability appears to be broken. Specifically, I've seen it fail with the `nerd-treeview:change-root` command.
#### Behavior

With the following structure:

```
└── directory-a
    └── directory-b
        ├── directory-c
        ├── directory-d
        │   └── directory-f
        │       ├── directory-g
        │       │   └── index.js
        │       └── directory-h
        │           └── index.js
        └── directory-e
```
1. Open tree view: <kbd>CMD</kbd> - <kbd>\</kbd>
2. Open `directory-a`, `directory-b`, `directory-d`, `directory-f`, `directory-g`, and `directory-h`: <kbd>o</kbd>
3. Change the root directory to `directory-b`: <kbd>C</kbd>
#### Current Outcome

The tree view root folder changes to highlighted `directory-b`, children directories lose their state and collapse.
#### Expected Outcome

The tree view root folder changes to highlighted `directory-b`, children directories retain their state and remain open (i.e. — `directory-b`, `directory-d`, `directory-f`, `directory-g`, and `directory-h` remain open).
#### Environment
- Mac OS X 10.11.3 (15D21)
- Atom 1.6.0
- nerd-treeview 0.4.0
- Default tree view key bindings disabled

**Comment by sQu1rr** [comment]
confirmed, U works as expected though which is interesting

**Comment by sQu1rr** [comment]
Need some testing before i'll release a patched version. Seem to work for me

**Comment by dcalhoun** [comment]
:+1: Yep, works for me as well.
