### ISSUE TITLE
navigate from nerdtree to already open file

### ISSUE THREAD

**Issue by CodisRedding** [sQu1rr/nerd-treeview#12]
How can I jump from nerd tree back over to the editor pane? In vim I would usually have ctrl+h,j,k,l to jump between windows to resolve this.

**Comment by sQu1rr** [comment]
Alt + \
Just like in original atom tree

**Comment by CodisRedding** [comment]
thanks, but how do you keep it from toggling the menu? I'd like to keep it open until I close it myself.

**Comment by sQu1rr** [comment]
are you on mac? C-0 then. see official atom bindings, i did not change them. i haven't really tested myself, maybe there is an update which screws things up?
