### ISSUE TITLE
Open file always creates new tab

### ISSUE THREAD

**Issue by dcalhoun** [sQu1rr/nerd-treeview#19]
### Steps to Reproduce
1. Open a file in the editor.
1. Focus on `nerd-treeview` via <kbd>C</kbd>-<kbd>0</kbd>.
1. Move highlight to a _different_ file from the one currently open in the editor.
1. Open a different file via <kbd>o</kbd> (`nerd-treeview:open`).

### Expected Result
File replaces currently open file.

### Current Result
File opens in a new tab, as if the user pressed <kbd>t</kbd> (`nerd-treeview:open-tab`).

### Environment
- nerd-treeview 0.5.3
- Atom 1.17.0
- macOS 10.12.4

**Comment by sQu1rr** [comment]
Will take a look/test next week. Thanks for the report.

**Comment by sQu1rr** [comment]
@dcalhoun - I tested on my atom 1.16 and it seems to work as expected. Does <kbd>o</kbd> always result in opening a file in a new tab for you? Did it start recently? Do you have native tree-view keybindings disabled?

**Comment by dcalhoun** [comment]
Thank you for looking into it.

- Yes, <kbd>o</kbd> always results in a new tab.
- Yes, it started recently—probably within the last month.
- Yes, I have `tree-view` keybindings disabled in my `atom/config.cson`:
  ```cson
  packagesWithKeymapsDisabled: [
    "tree-view"
  ]
  ```

I have also disabled all other thirty-party plugins and continue to experience the issue.

You likely need to upgrade to [Atom 1.17.0](https://github.com/atom/atom/releases/tag/v1.17.0) to experience the issue. One notable change is...
> Removal of jQuery from all bundled packages

**Comment by sQu1rr** [comment]
I can confirm this issue on 1.17.0, will look into it
