### ISSUE TITLE
Opening an already open file closes the file

### ISSUE THREAD

**Issue by dcalhoun** [sQu1rr/nerd-treeview#20]
### Steps to Reproduce
1. Open a directory with Atom
1. Open tree view (<kbd>C</kbd>-<kbd>\\</kbd>)
1. Open a file (<kbd>o</kbd>)
1. Focus tree view (<kbd>C</kbd>-<kbd>0</kbd>)
1. Open the same file (<kbd>o</kbd>)

### Expected Result
Focus is placed on the buffer for the selected file.

### Actual Result
Currently open file is closed. Focus is placed on empty buffer.

---

### Environment
- macOS 10.12.5
- Atom 1.17.2
- nerd-treeview 0.5.4

**Comment by sQu1rr** [comment]
Thanks will investigate next week
