### ISSUE TITLE
Opening a file with "stay" moves focus to buffer

### ISSUE THREAD

**Issue by dcalhoun** [sQu1rr/nerd-treeview#21]
### Steps to Reproduce
1. Open a directory with Atom
1. Open tree view (<kbd>C</kbd>-<kbd>\\</kbd>)
1. Open a file with stay...

**Stay Examples**
 - <kbd>g</kbd>-<kbd>s</kbd>
 - <kbd>g</kbd>-<kbd>i</kbd>
 - Have a file already open and then <kbd>g</kbd>-<kbd>o</kbd>

### Expected Result
Focus remains on tree view.

### Actual Result
Focus is placed on the buffer for the selected file.

---

### Environment
- macOS 10.12.5
- Atom 1.17.2
- nerd-treeview 0.5.4

**Comment by sQu1rr** [comment]
Thanks will investigate next week

**Comment by dcalhoun** [comment]
@sQu1rr Took me awhile, but I believe I've tracked this bug's origin to [your addition here](https://github.com/sQu1rr/nerd-treeview/commit/66c065bde2050c2a8aa6cb519857f7751c108b5b#diff-af5caca172504d6e4398803c1cae79b6R169). Do you remember why that was added? It seems to prevent "staying" altogether.

I tried removing `treeView.unfocus()` altogether, but that appears to break much more functionality (e.g. the tree collapses when opening a file, opening a file always creates a new tab).

**Comment by sQu1rr** [comment]
Hmmm thanks for investigating, sorry the issue has totally slipped my mind. I will see if that can be fixed later this week.

**Comment by dcalhoun** [comment]
@sQu1rr You're welcome. I actually think I've found the root cause and a proper fix. I'll open a PR shortly.
