### ISSUE TITLE
Split a file with "stay" moves focus to buffer

### ISSUE THREAD

**Issue by dcalhoun** [sQu1rr/nerd-treeview#23]
### Steps to Reproduce
1. Open a directory with Atom
1. Open tree view (<kbd>C</kbd>-<kbd>\\</kbd>)
1. Split/add tab a file with stay...

**Stay Examples**
 - <kbd>g</kbd>-<kbd>s</kbd>
 - <kbd>g</kbd>-<kbd>i</kbd>

### Expected Result
Focus remains on tree view.

### Actual Result
Focus is placed on the buffer for the selected file.

---

### Environment
- macOS 10.12.6
- Atom 1.19.0
- nerd-treeview 0.5.4

**Comment by dcalhoun** [comment]
From my research, this is actually a limitation of `atom/tree-view` that will need to be addressed. 

`nerd-treeview` [calls methods](https://github.com/sQu1rr/nerd-treeview/blob/v0.5.4/lib/nerd-treeview.coffee#L209-L221) that [do not pass along the `activatePane` option](https://github.com/atom/tree-view/blob/v0.217.6/lib/tree-view.coffee#L447-L457). A PR will need to be opened against `atom/tree-view` to support the [`options`](https://atom.io/docs/api/v1.19.0/Workspace#instance-open) hash passing through.

**Comment by sQu1rr** [comment]
should be fixed now, i simply refocus on tree-view if it is a stay command. hopefully that will work.
