### ISSUE TITLE
Does not open treeview when run in console.

### ISSUE THREAD

**Issue by vinchi777** [sQu1rr/nerd-treeview#3]
If I run atom in console. 
`
$ atom .
`
It cannot toggle the treeview

**Comment by sQu1rr** [comment]
does it produce any error?
i always run atom from terminal the way you show and the treeview is either there initially or i can successfully toggle it with ctrl+\

**Comment by vinchi777** [comment]
no it does not produce any error.
when I uninstall nerd-treeview. it works fine again when run in console.
I tried installing it again and the problem comes up again.

**Comment by vinchi777** [comment]
It works now. I tried install it through apm also I didnt disable tree-view keybindings.
