### ISSUE TITLE
[Feature] Search

### ISSUE THREAD

**Issue by liam-ngy** [sQu1rr/nerd-treeview#5]
Hey,

do you have any news about the search/filter function?
I'm really looking for it.

Best wishes,
Hoang

**Comment by sQu1rr** [comment]
hey atm i went back to vim and stopped improvements to this project. might come back later but feel free to hack around if you wish.

**Comment by forsigner** [comment]
+1

**Comment by nerdpad** [comment]
+1

**Comment by jordwalke** [comment]
@sQu1rr Curious why you went back to Vim? I go back and forth from time to time myself.

**Comment by sQu1rr** [comment]
@jordwalke For me atom is (was when I last used it) simply too slow, especially when I open many windows. Additionally when I ssh through terminal it is convenient to have the same IDE/config. I am using Neovim by the way.

**Comment by jordwalke** [comment]
Thanks for the info

**Comment by damassi** [comment]
@sQu1rr - Whoa, thanks for coming back to this! This little package saved Atom for me.

**Comment by damassi** [comment]
And I've been waiting for some kind of search for over two years now! https://github.com/atom/vim-mode/issues/576#issue-60891410.

**Comment by sQu1rr** [comment]
@damassi - glad you find it useful. search is really minimalistic..., and as I said before - I do not actively maintain the project any more. but i'll try to fix the issues if they arise
