### ISSUE TITLE
`tree-view:toggle` key binding doesn't work if project opened from CLI

### ISSUE THREAD

**Issue by dcalhoun** [sQu1rr/nerd-treeview#6]
If the tree view is collapsed when opening a new Atom window via the command line interface (i.e. - `atom /path/to/project`), the `tree-view:toggle` key binding does not work.
#### Behavior
1. `atom /path/to/project`
2. Ensure tree view is closed
3. Close Atom window
4. `atom /path/to/project`
5. <kbd>CMD</kbd> - <kbd>\</kbd>
#### Expected Outcome

The tree view opens.
#### Current Outcome

The tree view does _not_ open.
#### Environment
- Mac OS X 10.11.3 (15D21)
- Atom 1.5.4
- nerd-treeview 0.3.1
- Default Tree View bindings disabled.

**Comment by sQu1rr** [comment]
tree view is not initialised unless its opened, so i cannot interact with it before it is. hopefully delegating this task to treeview itself solves it, can you please test since i could not reproduce

**Comment by dcalhoun** [comment]
@sQu1rr thank you for the quick responses. You've made a great plugin. I appreciate your work. :smile:

**Comment by sQu1rr** [comment]
@dcalhoun Thanks for using it ;) I am actually not using atom myself any more. went back to vim. i feel that the main point of vim is performance, and atom is just too slow for me... I use it for markdown files though :)
