### ISSUE TITLE
"Toggle Vcs Ignore Files" key binding does not work

### ISSUE THREAD

**Issue by dcalhoun** [sQu1rr/nerd-treeview#7]
<kbd>Shift</kbd> - <kbd>H</kbd> does not appear to properly call the `nerd-treeview:toggle-cvs-ignored-files` command in nerd-treeview. Calling the `nerd-treeview:toggle-cvs-ignored-files` command directly in the command pallet correctly toggles Vcs ignored files. The key binding is the only thing not working at the moment.
##### Behavior
1. Open tree view
2. <kbd>Shift</kbd> - <kbd>H</kbd>
##### Expected Outcome

Vcs ignored files are toggled
##### Current Outcome

Vcs ignored files are _not_ toggled
##### Environment
- Mac OS X 10.11.3 (15D21)
- Atom 1.6.0
- nerd-treeview 0.3.1
- Default Tree View bindings disabled

**Comment by dcalhoun** [comment]
After looking at this more, this issue is likely caused by the fact that the <kbd>Shift</kbd> - <kbd>H</kbd> binding is also [bound to `nerd-treeview:move-to-top-of-screen`](https://github.com/sQu1rr/nerd-treeview/blob/v0.3.1/keymaps/vim-mode.cson#L29). The duplicate binding is probably destroying the `nerd-treeview:toggle-cvs-ignored-files` command key binding.

Which command should _actually_ use <kbd>Shift</kbd> - <kbd>H</kbd>? What key binding should the other command use?

**Comment by sQu1rr** [comment]
Thanks for investigating i'll look into it
